fix correct zip folder name + finalize step checks unit test output

diff --git a/.github/workflows/ubuntu_build_test.yml b/.github/workflows/ubuntu_build_test.yml
--- a/.github/workflows/ubuntu_build_test.yml
+++ b/.github/workflows/ubuntu_build_test.yml
@@ -160,6 +160,8 @@ jobs:
   gcc_unit_tests:
     runs-on: ubuntu-latest
     needs: [setup, gcc_compile]
+    outputs:
+      failed: ${{ steps.gcc_unit_tests.outputs.failed }}
     steps:
       - uses: actions/download-artifact@v4
         with:
@@ -179,21 +181,21 @@ jobs:
           name: gcc-debug-build
           path: .
 
-      - run: tar -xzf gcc-debug-build.tar.gz -C .
+      - run: tar -xzf gcc_debug_build.tar.gz -C .
 
       - uses: actions/download-artifact@v4
         with:
           name: gcc-release-build
           path: .
 
-      - run: tar -xzf gcc-release-build.tar.gz -C .
+      - run: tar -xzf gcc_release_build.tar.gz -C .
 
       - name: Run GCC unit tests
         run: |
           ./initRepo/scripts/build.sh -t -T -d -J --compiler gcc || TEST_FAILED=true
           ./initRepo/scripts/build.sh -t -T -r -J --compiler gcc || TEST_FAILED=true
           if [ "$TEST_FAILED" = true ]; then
-            exit 1
+            echo "failed=$( [ $rc -ne 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT
           fi
 
       - name: Publish GCC test results
@@ -274,6 +276,8 @@ jobs:
   clang_unit_tests:
     runs-on: ubuntu-latest
     needs: [setup, clang_compile]
+    outputs:
+      failed: ${{ steps.clang_unit_tests.outputs.failed }}
     steps:
       - uses: actions/download-artifact@v4
         with:
@@ -293,21 +297,21 @@ jobs:
           name: clang-debug-build
           path: .
 
-      - run: tar -xzf clang-debug-build.tar.gz -C .
+      - run: tar -xzf clang_debug_build.tar.gz -C .
 
       - uses: actions/download-artifact@v4
         with:
           name: clang-release-build
           path: .
 
-      - run: tar -xzf clang-release-build.tar.gz -C .
+      - run: tar -xzf clang_release_build.tar.gz -C .
 
       - name: Run GCC unit tests
         run: |
           ./initRepo/scripts/build.sh -t -T -d -J --compiler clang || TEST_FAILED=true
           ./initRepo/scripts/build.sh -t -T -r -J --compiler clang || TEST_FAILED=true
           if [ "$TEST_FAILED" = true ]; then
-            exit 1
+            echo "failed=$( [ $rc -ne 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT
           fi
 
       - name: Publish Clang test results
@@ -362,7 +366,7 @@ jobs:
 
   finalize:
     runs-on: ubuntu-latest
-    needs: [shellcheck, clang_format, clang_tidy, gcc_compile, clang_compile]
+    needs: [shellcheck, clang_format, clang_tidy, gcc_compile, clang_compile, clang_unit_tests, gcc_unit_tests]
     if: always()
     steps:
       - run: |
@@ -374,6 +378,8 @@ jobs:
           if [ "${{ needs.clang_tidy.outputs.failed }}" = "true" ]; then failed=true; echo " - clang-tidy: FAILED"; else echo " - clang-tidy: OK"; fi
           if [ "${{ needs.gcc_compile.outputs.failed }}" = "true" ]; then failed=true; echo " - gcc builds: FAILED"; else echo " - gcc builds: OK"; fi
           if [ "${{ needs.clang_compile.outputs.failed }}" = "true" ]; then failed=true; echo " - clang builds: FAILED"; else echo " - clang builds: OK"; fi
+          if [ "${{ needs.clang_unit_tests.outputs.failed }}" = "true" ]; then failed=true; echo " - clang unit tests: FAILED"; else echo " - clang unit tests: OK"; fi
+          if [ "${{ needs.gcc_unit_tests.outputs.failed }}" = "true" ]; then failed=true; echo " - gcc unit tests: FAILED"; else echo " - gcc unit tests: OK"; fi
 
           if $failed; then exit 1; fi
 
